# Generated by Django 3.2.4 on 2023-07-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposttable',
            name='slug',
        ),
    ]
